# Generated by Django 4.2.16 on 2024-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
