# Generated by Django 4.2.16 on 2024-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.ManyToManyField(blank=True, related_name='doctor_working_days', to='doctors.workingday'),
        ),
    ]
