# Generated by Django 4.2.16 on 2024-09-25 23:11

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialization',
            old_name='specialization',
            new_name='title',
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='specialization/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
    ]
