# Generated by Django 4.2.16 on 2024-10-06 20:27

from django.db import migrations, models
import django.utils.timezone
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_address_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, validators=[doctors.models.validate_date_of_birth]),
            preserve_default=False,
        ),
    ]
