# Generated by Django 4.2.16 on 2024-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_end_time_doctor_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
