# Generated by Django 4.2.16 on 2024-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctor_working_days', to='doctors.workingday'),
        ),
    ]
