# Generated by Django 4.2.16 on 2024-10-06 18:43

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_address_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(validators=[patients.models.validate_date_of_birth]),
        ),
    ]
