# Generated by Django 4.2.16 on 2024-10-06 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid egyptian phone number.', regex='^(010|011|015|012)\\d{8}$')]),
        ),
    ]
